### ISSUE TITLE
(Fix) Rename repository

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/deployment-azure#29]
Problem:
Repository has ambiguous name `test` and `templates`
- it contains not only test branches
- templates, it's more like scripts

Solution:
- rename repository to `deployment-azure`
  - deployment means this repo is used to deploy stuff
  - azure means this repo is used to deploy to Azure
- create an empty repository with `test-template` with README with a link to a new repository
- update wiki and instructions

**Comment by phahulin** [comment]
Repository renamed, links updated
